.test-jobs-common:
  stage: test
  image: registry.gitlab.com/xen-project/xen/${CONTAINER}
  except:
    - master
    - smoke
    - /^coverity-tested\/.*/
    - /^stable-.*/

.riscv64-test-needs: &riscv64-test-needs
  - qemu-system-riscv64-8.2.0-riscv64-export
  - kernel-6.4-riscv64-export
  - busybox-1.31.6-riscv64-rootfs-export

.riscv64-aia-test-needs: &riscv64-aia-test-needs
  - kernel-6.6-aia-support-riscv64-export
  - qemu-system-riscv64-8.2.0-aia-riscv64-export
  - busybox-aia-1.31.6-riscv64-rootfs-export

.qemu-riscv64:
  extends: .test-jobs-common
  variables:
    CONTAINER: archlinux:current-riscv64
    LOGFILE: qemu-smoke-riscv64.log
  artifacts:
    paths:
      - smoke.serial
      - '*.log'
    when: always
  tags:
    - x86_64

# Test jobs
build-each-commit-gcc:
  extends: .test-jobs-common
  variables:
    CONTAINER: debian:stretch
    XEN_TARGET_ARCH: x86_64
    CC: gcc
  script:
    - BASE=${BASE_SHA:-${CI_COMMIT_BEFORE_SHA}} TIP=${TIP_SHA:-${CI_COMMIT_SHA}} ./automation/gitlab-ci/build-each-commit.sh 2>&1 | tee ../build-each-commit-gcc.log
    - mv ../build-each-commit-gcc.log .
  artifacts:
    paths:
      - '*.log'
    when: always
  needs: []
  tags:
    - x86_64

qemu-smoke-riscv64-gcc-dom0:
  extends: .qemu-riscv64
  script:
    - ./automation/scripts/qemu-smoke-riscv64.sh dom0-test 2>&1 | tee ${LOGFILE}
  needs:
    - archlinux-current-gcc-riscv64-debug
    - *riscv64-test-needs

qemu-smoke-riscv64-gcc-dom0-smp:
  extends: .qemu-riscv64
  script:
    - ./automation/scripts/qemu-smoke-riscv64.sh dom0-smp-test 2>&1 | tee ${LOGFILE}
  needs:
    - archlinux-current-gcc-riscv64-debug
    - *riscv64-test-needs

qemu-smoke-riscv64-gcc-dom0less-4smp-1vcpu:
  extends: .qemu-riscv64
  script:
    - ./automation/scripts/qemu-smoke-riscv64.sh dom0less-4smp-1vcpu-test 2>&1 | tee ${LOGFILE}
  needs:
    - archlinux-current-gcc-riscv64-debug
    - *riscv64-test-needs

qemu-smoke-riscv64-gcc-dom0less-4smp-1vcpu-aplic-msic:
  extends: .qemu-riscv64
  script:
    - ./automation/scripts/qemu-smoke-riscv64.sh dom0less-4smp-1domu-2vcpu-aplic-msic-test 2>&1 | tee ${LOGFILE}
  needs:
    - archlinux-current-gcc-riscv64-debug
    - *riscv64-aia-test-needs
